---
- name: Install nginx

  apt:

    name: nginx

    state: present

  notify: Restart nginx



- name: Update default Nginx page

  copy:

    content: "Hello from Ansible!"

    dest: /var/www/html/index.html

  notify: Restart nginx
